(()=>{
'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const accounts=[{id:'customer-a',contact:'林澄',name:'澄川科技',phone:'13910001001'},{id:'customer-b',contact:'周宁',name:'远山设计',phone:'13910001002'}];
let identity=null,tab='intro',pendingRoom=null,filters={text:'',area:'all',rent:'all',sort:'default'};
try{identity=accounts.find(a=>a.id===sessionStorage.getItem('park-customer-identity'))||null}catch{}
const button=(label,action,attrs='',primary=false)=>'<button class="'+(primary?'primary':'')+'" data-action="'+action+'" '+attrs+'>'+label+'</button>';
const masked=p=>p.slice(0,3)+'****'+p.slice(-4);
function data(){return ParkStore.read()}
function publicAd(id,d=data()){return d.ads.find(a=>a.room===id&&a.status==='已发布')}
function available(d=data()){return d.ads.filter(a=>a.status==='已发布').map(a=>({ad:a,room:d.rooms.find(r=>r.id===a.room)})).filter(x=>x.room&&x.room.status==='空置')}
function spaceName(r){return r.id.split('-')[0]+' 座 · '+r.area+'㎡ '+(r.area>=200?'研发办公空间':'独立办公空间')}
function tell(text){const t=$('#customer-toast');t.textContent=text;t.hidden=false;clearTimeout(window.customerTimer);window.customerTimer=setTimeout(()=>t.hidden=true,3200)}
function route(){return location.hash.slice(1)||'home'}
function nav(to){if(route()===to){render();window.scrollTo(0,0)}else location.hash=to}
function header(){let r=route(),active=r.startsWith('space/')?'spaces':r;return '<header class="site-header"><a class="brand" href="#home"><span class="brand-mark">360</span><span>星桥科创园<small>STARBRIDGE PARK</small></span></a><nav class="site-nav" aria-label="客户招商导航">'+[['home','园区首页'],['spaces','找空间'],['amenities','园区配套'],['applications','我的申请']].map(([k,t])=>'<a href="#'+k+'" class="'+(active===k?'active':'')+'">'+t+'</a>').join('')+'</nav><div class="head-actions">'+button(identity?'体验账户 · '+esc(identity.contact):'登录体验','account','class="quiet"')+'<a class="switch-entry" href="index.html">切换入口 ↗</a></div></header>'}
function footer(){return '<footer class="site-footer"><span>360 智慧园区 · 星桥科创园招商服务</span><span>交互原型 · 园区、房源及价格均为演示信息 · 图片为概念示意</span></footer>'}
function card(x,i=0){let r=x.room;return '<a class="listing" href="#space/'+encodeURIComponent(r.id)+'"><div class="listing-cover"><img src="campus-hero.png" style="object-position:'+([75,35,55,90][i%4])+'% center" alt="园区概念环境图" loading="lazy"><span class="tag">可预约看房</span><span class="image-note">概念示意</span></div><h3>'+spaceName(r)+'</h3><p class="info">'+esc(r.id)+' · '+Math.floor(Number(r.id.split('-')[1])/100)+' 层 · '+esc(r.tag)+'</p><div class="listing-bottom"><span class="price">'+r.price+'<small> 元/㎡/月起</small></span><span class="text-link">查看空间 ↗</span></div></a>'}
function services(){return '<section class="services" id="amenities"><div class="wrap"><div class="section-head"><div><span class="eyebrow">MORE THAN A WORKPLACE</span><h2>让专注工作，成为日常</h2><p>空间之外，为团队提供日常所需的园区服务。</p></div></div><div class="service-grid">'+[['01','共享会议空间','从小组讨论到客户交流，选择适合团队的沟通空间。'],['02','日常生活配套','餐饮与休憩空间，让工作与生活保持舒适的节奏。'],['03','园区服务支持','招商顾问协助看房与签约，入驻后由物业客服对接。']].map(([n,t,p])=>'<div class="service-item"><span>'+n+' / PARK SERVICES</span><h3>'+t+'</h3><p>'+p+'</p></div>').join('')+'</div></div></section>'}
function visit(){return '<section class="wrap"><div class="visit-strip"><div><h2>下一处办公空间，亲自来看看</h2><p>选择意向房源与到访时间，让招商顾问帮您安排。</p></div><a href="#spaces" class="button primary">挑选房源，预约看房 →</a></div></section>'}
function home(){let list=available();return '<main><section class="hero"><img src="campus-hero.png" class="hero-img" alt="星桥科创园概念场景"><div class="hero-overlay"></div><div class="hero-copy"><span class="eyebrow light">A PLACE FOR YOUR NEXT CHAPTER</span><h1>星桥科创园<span>给下一步生长，合适的空间</span></h1><p>从独立办公室到研发空间，在这里找到团队的新起点。</p><a class="button primary" href="#spaces">探索在租空间 →</a></div><div class="hero-bottom"><span>办公 · 研发 · 园区服务</span><span>园区概念示意 / STARBRIDGE</span></div></section><section class="wrap section"><div class="section-head"><div><span class="eyebrow">AVAILABLE SPACES</span><h2>为您的团队，挑一处好空间</h2><p>浏览面积与挂牌租金，在线预约到访。</p></div><a class="text-link" href="#spaces">查看全部 '+list.length+' 处空间 →</a></div><div class="listing-grid">'+list.slice(0,3).map(card).join('')+'</div>'+(!list.length?'<div class="no-results">当前暂无公开在租房源，请稍后再来查看。</div>':'')+'</section>'+services()+visit()+'</main>'}
function option(value,label,current){return '<option value="'+value+'" '+(value===current?'selected':'')+'>'+label+'</option>'}
function spaces(){let list=available().filter(x=>{let r=x.room;return (spaceName(r)+r.id+r.tag).toLowerCase().includes(filters.text.toLowerCase())&&(filters.area==='all'||(filters.area==='small'?r.area<150:filters.area==='mid'?r.area>=150&&r.area<=250:r.area>250))&&(filters.rent==='all'||(filters.rent==='low'?r.price<=70:r.price>70))});if(filters.sort==='price')list.sort((a,b)=>a.room.price-b.room.price);if(filters.sort==='area')list.sort((a,b)=>a.room.area-b.room.area);
 return '<main class="wrap"><div class="page-top"><span class="eyebrow">FIND YOUR SPACE</span><h1>找到适合团队的空间</h1><p>公开在租房源，价格与可预约状态同步更新。</p></div><form id="filters" class="filter-panel"><div class="filter-field"><label for="search-text">房源关键词</label><input id="search-text" name="text" placeholder="房号 / 精装修 / 办公" value="'+esc(filters.text)+'"></div><div class="filter-field"><label for="search-area">面积</label><select id="search-area" name="area">'+[['all','不限面积'],['small','150㎡以下'],['mid','150–250㎡'],['large','250㎡以上']].map(([v,t])=>option(v,t,filters.area)).join('')+'</select></div><div class="filter-field"><label for="search-rent">挂牌租金</label><select id="search-rent" name="rent">'+[['all','不限价格'],['low','70元/㎡/月及以下'],['high','70元/㎡/月以上']].map(([v,t])=>option(v,t,filters.rent)).join('')+'</select></div><button type="submit" class="primary">查找空间</button>'+button('重置','reset-filters','type="button"')+'</form><div class="result-line"><span>找到 '+list.length+' 处可预约空间</span><label>排序 <select id="sort" style="width:auto;padding:7px 10px">'+[['default','默认推荐'],['price','价格从低到高'],['area','面积从小到大']].map(([v,t])=>option(v,t,filters.sort)).join('')+'</select></label></div><div class="listing-grid">'+list.map(card).join('')+'</div>'+(!list.length?'<div class="no-results"><h2>暂时没有匹配的空间</h2><p>试试放宽面积或价格条件。</p>'+button('清空筛选','reset-filters')+'</div>':'')+'<div class="section"></div></main>'}
function floorplan(){return '<svg class="floorplan" viewBox="0 0 620 280" role="img" aria-label="办公空间布局示意，非测绘图"><rect x="20" y="20" width="580" height="225" fill="white" stroke="#657083" stroke-width="5"/><path d="M425 20V245M425 130H600M140 20V105H20" stroke="#657083" stroke-width="3" fill="none"/><path d="M60 245H130" stroke="white" stroke-width="8"/><path d="M60 245V180A65 65 0 0 1 125 245" stroke="#006bff" fill="none"/><text x="175" y="140" fill="#657083" font-size="17">灵活办公区</text><text x="460" y="80" fill="#657083" font-size="15">会议区</text><text x="460" y="190" fill="#657083" font-size="15">洽谈区</text><text x="65" y="265" fill="#006bff" font-size="12">入口</text></svg><p class="muted">布局仅为功能示意，实际交付以现场勘察为准。</p>'}
function detail(id){let d=data(),ad=publicAd(id,d),r=d.rooms.find(r=>r.id===id);if(!ad||!r)return '<main class="wrap section"><div class="no-results"><h2>该房源已下架</h2><p>您可以继续查看其他公开在租空间。</p><a class="button primary" href="#spaces">返回房源列表</a></div></main>';let isOpen=r.status==='空置';return '<main class="wrap"><div class="crumb"><a href="#spaces">找空间</a> / '+esc(id)+'</div><div class="detail-grid"><div class="detail-image"><img src="campus-hero.png" alt="园区概念环境图"><small>园区概念示意</small></div><div class="detail-summary"><span class="status-tag '+(isOpen?'':'closed')+'">'+(isOpen?'在租 · 可预约':'暂不可预约')+'</span><h1>'+spaceName(r)+'</h1><p class="muted">'+esc(ad.sub)+'</p><div class="price">'+r.price+'<small> 元/㎡/月起</small></div><p class="muted" style="font-size:12px">参考月租 ¥'+(r.price*r.area).toLocaleString()+'，具体条款以签约确认为准。</p><div class="detail-facts"><div><strong>'+r.area+'㎡</strong><small>建筑面积</small></div><div><strong>'+Math.floor(Number(id.split('-')[1])/100)+'F</strong><small>所在楼层</small></div><div><strong>'+esc(r.tag)+'</strong><small>空间标签</small></div></div><p class="muted" style="font-size:12px">房源编号 '+id+' · 星桥科创园</p>'+button(isOpen?'预约看房 →':'房源已被占用，暂不可预约','apply','data-room="'+esc(id)+'" '+(isOpen?'':'disabled'),true)+'</div></div><div class="detail-tabs" role="tablist">'+[['intro','空间介绍'],['layout','布局示意'],['services','园区服务']].map(([k,t])=>'<button role="tab" aria-selected="'+(tab===k)+'" class="'+(tab===k?'active':'')+'" data-action="detail-tab" data-tab="'+k+'">'+t+'</button>').join('')+'</div><div class="detail-body" role="tabpanel">'+(tab==='layout'?floorplan():tab==='services'?'<div class="amenity-list"><span>共享会议空间</span><span>招商顾问对接</span><span>物业客服</span><span>日常餐饮配套</span><span>公共休憩空间</span><span>入驻流程协助</span></div><p>服务配置为演示内容，到访时可进一步确认。</p>':'<h3>适合团队当下，也为成长预留余地</h3><p style="margin-top:15px">'+r.area+'㎡'+esc(r.tag)+'空间，可结合办公、研发和会议需求沟通布局。预约到访后，由招商顾问介绍具体交付条件及租赁方案。</p><div class="amenity-list"><span>独立办公空间</span><span>灵活功能分区</span><span>园区服务支持</span></div>')+'</div></main>'}
const phases=['已提交','顾问接洽','预约带看','方案沟通','已签约'];
function applications(){let d=data();if(!identity)return '<main class="wrap section"><div class="no-results"><span class="eyebrow">MY APPLICATIONS</span><h2>查看您的看房申请</h2><p>选择体验账户，查看该账户提交的预约和进度。</p>'+button('登录体验','account','',true)+'</div></main>';let list=d.leads.filter(l=>l.phone===identity.phone);
 return '<main class="wrap"><div class="page-top"><span class="eyebrow">MY APPLICATIONS</span><h1>我的申请</h1><p>从预约看房到方案确认，每一步进展都在这里。</p></div><div class="account-bar"><div><h2>'+esc(identity.contact)+' · '+esc(identity.name)+'</h2><p>'+masked(identity.phone)+' · 仅展示当前体验账户的申请</p></div>'+button('切换体验账户','account')+'</div>'+list.map(l=>{let o=d.opps.find(o=>o.leadId===l.id),step=o?({'初步接洽':1,'实地带看':2,'商务谈判':3,'已签约':4}[o.stage]??1):0,ended=l.status==='无效';return '<article class="application"><div class="application-head"><div><h2>'+esc(l.applications.find(a=>a.room)?.room||'园区空间咨询')+' · 看房申请</h2><p>申请编号 AP-'+l.id+' · '+esc(l.applications[0].date)+'</p></div><span class="status-tag '+(ended?'closed':'')+'">'+(ended?'已结束':phases[step])+'</span></div><div class="progress-track">'+phases.map((t,i)=>'<div class="progress-step '+(!ended&&i<=step?'done':'')+'">'+String(i+1).padStart(2,'0')+' '+t+'<div class="step-line"></div></div>').join('')+'</div><div class="application-note">'+(ended?'本次咨询已结束，如仍有空间需求，欢迎重新联系园区。':step===0?'您的申请已提交，招商顾问将与您联系确认到访安排。':step===1?'招商顾问正在与您对接，您可以进一步沟通空间需求。':step===2?'已进入带看阶段，具体到访安排请与招商顾问确认。':step===3?'正在沟通租赁方案，请与招商顾问确认交付及商务条款。':'合同签约已完成，园区将协助办理后续入驻事项。')+'</div><div class="application-records"><strong>我的提交记录 · '+l.applications.length+' 次</strong>'+l.applications.map(a=>'<p>'+esc(a.date)+' · '+esc(a.room||'空间咨询')+(a.visit?' · 期望到访 '+esc(a.visit)+' '+esc(a.slot):'')+'<br>'+esc(a.need)+'</p>').join('')+'</div></article>'}).join('')+(!list.length?'<div class="no-results"><h2>还没有提交看房申请</h2><p>先看看园区有哪些适合您的空间。</p><a href="#spaces" class="button primary">去找空间 →</a></div>':'')+'<div class="section"></div></main>'}
function render(){let r=route(),content;if(r==='spaces')content=spaces();else if(r==='applications')content=applications();else if(r==='amenities')content='<main><div class="wrap page-top"><span class="eyebrow">LIFE AT STARBRIDGE</span><h1>园区配套与服务</h1><p>让团队专注业务，把日常交给园区。</p></div>'+services()+visit()+'</main>';else if(r.startsWith('space/'))content=detail(decodeURIComponent(r.slice(6)));else content=home();$('#customer-app').innerHTML=header()+content+footer()}
function close(){let dialog=$('#dialog-root dialog');dialog?.close();$('#dialog-root').innerHTML=''}
function modal(title,content){close();$('#dialog-root').innerHTML='<dialog aria-label="'+esc(title)+'"><div class="dialog-head"><h2>'+esc(title)+'</h2>'+button('✕','close-dialog','aria-label="关闭弹窗"')+'</div><div class="dialog-body">'+content+'</div></dialog>';let d=$('#dialog-root dialog');d.showModal();d.addEventListener('click',e=>{if(e.target===d)close()});d.addEventListener('cancel',()=>{pendingRoom=null})}
function login(){modal('选择客户体验账户','<p class="form-note">以下为原型演示账户，用于体验“我的申请”。不进行真实手机号验证。</p>'+accounts.map(a=>'<button class="account-choice" data-action="choose-account" data-id="'+a.id+'"><strong>'+esc(a.contact)+' · '+esc(a.name)+'</strong><small>'+masked(a.phone)+' · 客户体验账户 '+(a.id==='customer-a'?'A':'B')+'</small></button>').join('')+(identity?button('退出当前体验账户','logout'):'') )}
function apply(id){let d=data(),a=publicAd(id,d),r=d.rooms.find(r=>r.id===id);if(!a||r?.status!=='空置')return tell('该房源当前不可预约，请查看其他空间');if(!identity){pendingRoom=id;login();return}modal('预约看房 · '+id,'<form id="appointment" class="form-grid"><div class="field full form-note">'+spaceName(r)+' · '+r.price+' 元/㎡/月起</div><input type="hidden" name="room" value="'+esc(id)+'"><div class="field"><label for="contact">联系人</label><input id="contact" name="contact" value="'+esc(identity.contact)+'" readonly></div><div class="field"><label for="phone">联系电话</label><input id="phone" name="phone" value="'+identity.phone+'" readonly></div><div class="field full"><label for="company">企业 / 客户名称</label><input id="company" name="name" value="'+esc(identity.name)+'" required maxlength="80"></div><div class="field"><label for="visit">期望到访日期</label><input id="visit" name="visit" type="date" value="'+ParkModel.add(d.today,1)+'" min="'+d.today+'" required></div><div class="field"><label for="slot">期望时段</label><select id="slot" name="slot"><option>上午 09:00–12:00</option><option>下午 14:00–18:00</option></select></div><div class="field full"><label for="need">空间需求</label><textarea id="need" name="need" rows="3" maxlength="500" placeholder="团队人数、面积需求、预计入驻时间等" required></textarea></div><label class="consent full"><input type="checkbox" required><span>同意将以上信息提供给园区招商团队，用于本次预约联系。</span></label><div class="form-error full" id="submit-error" role="alert"></div><button type="submit" class="primary full">提交看房申请</button></form>')}
function submit(form){let d=data(),v=Object.fromEntries(new FormData(form)),ad=publicAd(v.room,d);try{if(!identity)throw Error('请先选择体验账户');if(!ad||d.rooms.find(r=>r.id===v.room)?.status!=='空置')throw Error('该房源已失效或被占用，请返回选择其他空间');if(v.visit<d.today)throw Error('到访日期不能早于当前日期');let result=ParkModel.lead(d,{name:v.name.trim(),contact:identity.contact,phone:identity.phone,need:v.need.trim(),source:'招商门户',adId:ad.id});let item=result.record.applications.at(-1);Object.assign(item,{room:v.room,visit:v.visit,slot:v.slot});ad.submissions=(ad.submissions||0)+1;ad.intents=new Set(d.leads.filter(l=>l.applications.some(a=>a.adId===ad.id)).map(l=>l.phone)).size;ParkStore.write(d);pendingRoom=null;modal('申请已提交','<div class="success-copy"><div class="success-mark">✓</div><h2>期待与您在园区见面</h2><p>已收到您的看房申请。具体到访时间将由招商顾问与您确认。'+(result.merged?'<br>本次需求已合并到您的客户申请记录。':'')+'</p>'+button('查看我的申请','view-applications','',true)+'</div>')}catch(e){$('#submit-error').textContent=e.message}}
document.addEventListener('click',e=>{let target=e.target.closest('[data-action]');if(!target||target.disabled)return;let action=target.dataset.action;if(action==='account'){pendingRoom=null;login()}else if(action==='choose-account'){identity=accounts.find(a=>a.id===target.dataset.id);try{sessionStorage.setItem('park-customer-identity',identity.id)}catch{}let id=pendingRoom;close();render();if(id){pendingRoom=null;apply(id)}}else if(action==='logout'){identity=null;try{sessionStorage.removeItem('park-customer-identity')}catch{}close();render()}else if(action==='close-dialog'){pendingRoom=null;close()}else if(action==='apply')apply(target.dataset.room);else if(action==='view-applications'){close();nav('applications')}else if(action==='reset-filters'){filters={text:'',area:'all',rent:'all',sort:'default'};render()}else if(action==='detail-tab'){tab=target.dataset.tab;let y=scrollY;render();scrollTo(0,y)}});
document.addEventListener('submit',e=>{if(e.target.id==='filters'){e.preventDefault();filters={...filters,...Object.fromEntries(new FormData(e.target))};render()}else if(e.target.id==='appointment'){e.preventDefault();submit(e.target)}});
document.addEventListener('change',e=>{if(e.target.id==='sort'){filters.sort=e.target.value;render()}});
function countView(){let routeValue=route();if(routeValue.startsWith('space/')){let d=data(),a=publicAd(decodeURIComponent(routeValue.slice(6)),d);if(a){a.views=(a.views||0)+1;ParkStore.write(d)}}}
window.addEventListener('hashchange',()=>{tab='intro';countView();render();scrollTo(0,0)});
window.addEventListener('storage',e=>{if(e.key===ParkStore.key&&!$('#dialog-root dialog[open]'))render()});
window.addEventListener('focus',()=>{if(!$('#dialog-root dialog[open]'))render()});
countView();render();
window.CustomerDemo={render,available:()=>available().map(x=>x.room.id)};
})();
