const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const browser = await chromium.launch({
    headless: true,
    executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
  });
  try {
    const page = await browser.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('dialog', dialog => dialog.accept());
    await page.goto(pathToFileURL(path.join(__dirname, '../miniprogram-view.html')).href);
    assert.equal(await page.locator('html').getAttribute('data-product-version'), '2.0.0');
    assert.equal(await page.locator('#quick-booking-form .required-hint').count(), 0);
    assert.deepEqual(await page.locator('#home .service-item').evaluateAll(items => items.map(item => item.dataset.page)), ['visitor','repair','vehicle','feedback']);
    assert.equal(await page.locator('#home .service-item[data-page="vehicle"]').textContent(), '车辆服务');
    assert.equal(await page.locator('#home .v2-services-card > .service-grid').count(), 1);
    assert.equal(await page.locator('#home .v2-services-card > .v2-notice-entry').count(), 1);
    assert.equal(await page.locator('#home .service-grid').evaluate(el => getComputedStyle(el).boxShadow), 'none');
    await page.locator('.v2-notice-entry').click();
    assert(await page.locator('#notices').isVisible());
    await page.locator('.nav-back').click();
    assert(await page.locator('#home').isVisible());
    assert.equal(await page.locator('#profile .profile-menu-row[data-page="meeting"],#profile .profile-menu-row[data-page="visitor"],#profile .profile-menu-row[data-page="repair"]').count(), 0);
    assert.deepEqual(await page.locator('#profile .profile-menu-row b').allTextContents(), ['我的车辆','我的咨询','我的反馈','隐私与授权']);
    await page.evaluate(() => window.__showMiniPage('meeting'));
    assert.equal(await page.locator('#meeting .my-bookings-button').evaluate(el => getComputedStyle(el).position), 'static');
    assert.equal(await page.locator('#meeting').evaluate(el => getComputedStyle(el, '::after').content), 'none');
    await page.locator('#meeting .field-title .my-bookings-button').click();
    assert(await page.locator('#my-bookings').isVisible());
    await page.locator('.nav-back').click();
    assert(await page.locator('#meeting').isVisible());
    assert.deepEqual(await page.locator('#home .space-info .meta > span').allTextContents(), ['6F','可分割']);
    assert.equal(await page.locator('#contact-modal .form-row .required-mark').count(), 3);
    assert.equal(await page.locator('#contact-modal .form-row [aria-required="true"]').count(), 3);
    assert.equal(await page.locator('.agreement .required-mark').count(), 0);
    assert.equal(await page.locator('#quick-booking-form input[type="checkbox"]').evaluate(el => el.required), true);
    assert.equal(await page.locator('#contact-email').evaluate(el => el.required), false);
    assert.equal(await page.locator('label[for="quick-purpose"] .required-mark').count(), 0);
    assert.match(await page.locator('label[for="quick-purpose"]').textContent(), /选填/);
    const show = id => page.evaluate(id => window.__showMiniPage(id), id);
    await show('home');
    const featured = page.locator('#home>.space.card');
    await featured.locator('img').click();
    assert(await page.locator('#space-detail').isVisible());
    assert.equal(await page.locator('#space-detail-title').textContent(), 'A-605 · 研发办公');
    assert.match(await page.locator('#space-detail-meta').textContent(), /A座 · 6F · 320㎡/);
    assert.match(await page.locator('#space-detail-price').textContent(), /¥70/);
    assert.equal(await page.locator('#space-detail-image').getAttribute('src'), 'miniprogram/assets/campus-hero.jpg');
    await page.locator('#space-contact-open').click();
    assert(await page.locator('#contact-modal').isVisible());
    await page.locator('#contact-modal').evaluate(el => el.classList.add('hidden'));
    await page.locator('.nav-back').click();
    assert(await page.locator('#home').isVisible());
    for (const key of ['Enter', 'Space']) {
      await featured.focus();
      await page.keyboard.press(key);
      assert(await page.locator('#space-detail').isVisible());
      await page.locator('.nav-back').click();
      assert(await page.locator('#home').isVisible());
    }
    for (const id of ['my-bookings','visitor-records','repair-records']) {
      await show(id);
      if(id==='visitor-records')assert.equal(await page.locator('#visitor-records > .service-notice').count(), 0);
      assert.equal(await page.locator(`#${id} .booking-record`).count(), 2);
      if(id==='my-bookings')await page.locator('#my-bookings .reservation-main').first().click();
      else await page.locator(`#${id} .booking-record`).first().click();
      if(id==='my-bookings')await page.getByRole('button', { name: '查看本次预约', exact: true }).click();
      const recordText = await page.locator('.screen > section:not(.hidden)').last().textContent();
      assert.match(recordText, /编号/);
      assert.doesNotMatch(recordText, /演示|示例|样例|未发送|非真实/);
    }
    assert.deepEqual(await page.evaluate(() => ['bookings','visitors','repairs'].map(k => MiniStore.data[k].length)), [0,0,0]);
    assert.deepEqual(await page.locator('.profile-stats b').allTextContents(), ['2','2','2']);
    await show('repair');
    assert.deepEqual(await page.locator('#repair .form-row input,#repair .service-select-trigger').evaluateAll(items => items.map(item => getComputedStyle(item).height)), ['30px','30px','30px','30px','30px']);
    const locationSelect = page.locator('#repair .service-select-trigger').first();
    await locationSelect.click();
    await page.locator('.service-select-panel.open').getByRole('option', { name: 'B座', exact: true }).click();
    assert.equal(await page.locator('#repair select').first().inputValue(), 'B座');
    assert.equal(await locationSelect.getAttribute('aria-expanded'), 'false');
    await locationSelect.press('ArrowDown');
    assert.equal(await page.locator('.service-select-panel.open [aria-selected="true"]').textContent(), 'B座');
    await page.keyboard.press('ArrowUp');
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#repair select').first().inputValue(), 'A座');
    await locationSelect.click();
    await page.keyboard.press('Escape');
    assert.equal(await locationSelect.getAttribute('aria-expanded'), 'false');
    await show('feedback');
    await page.locator('#feedback .service-select-trigger').click();
    await page.locator('.service-select-panel.open').getByRole('option', { name: '物业投诉', exact: true }).click();
    assert.equal(await page.locator('#feedback select').inputValue(), '物业投诉');
    assert.equal(await page.locator('#feedback .required-hint').count(), 0);
    assert.equal(await page.locator('#feedback select').getAttribute('required'), null);
    assert.equal(await page.locator('#feedback .service-select-trigger').getAttribute('aria-required'), 'false');
    await page.locator('#feedback .service-select-trigger').click();
    await page.locator('.service-select-panel.open').getByRole('option', { name: '请选择反馈类型（选填）', exact: true }).click();
    await page.locator('#feedback textarea').fill('选填电话留空的反馈');
    await page.locator('#feedback .primary-button').click();
    assert.equal(await page.evaluate(() => MiniStore.data.feedback.length), 0);
    await page.locator('#feedback .agreement input').check();
    await page.locator('#feedback .primary-button').click();
    assert.equal(await page.evaluate(() => MiniStore.data.feedback.length), 1);
    assert.equal(await page.evaluate(() => MiniStore.data.feedback[0].title), '意见反馈');
    const filter = async (section, index, text) => {
      const label = page.locator(`#${section} .meeting-filters label`).nth(index);
      await label.locator('.filter-trigger').click();
      await label.getByRole('button', { name: text, exact: true }).click();
    };
    await show('spaces');
    await filter('spaces', 0, 'B座');
    assert.equal(await page.locator('.building-card:visible').count(), 1);
    await page.locator('.building-card:visible').click();
    await page.locator('[data-space-detail="B-503"]').click();
    assert.match(await page.locator('#space-detail-meta').innerText(), /^B座/);
    await page.locator('.nav-back').click();
    assert(await page.locator('#building-detail').isVisible());
    await show('spaces');
    await filter('spaces', 0, 'D座');
    assert.equal(await page.locator('.building-card:visible').count(), 0);
    assert(await page.getByText('暂无符合条件的结果，请调整筛选条件。', { exact: true }).first().isVisible());
    await show('meeting');
    await filter('meeting', 0, 'C区');
    assert.equal(await page.locator('.meeting-list-card:visible').count(), 1);
    assert.match(await page.locator('.meeting-list-card:visible').innerText(), /云杉/);
    await filter('meeting', 0, '全部区域');
    await page.locator('.meeting-card-detail[data-room-detail="远山路演厅"]').click();
    assert.match(await page.locator('#meeting-detail > .meta').innerText(), /24人/);
    assert.match(await page.locator('#meeting-detail .detail-price').innerText(), /180/);
    await page.locator('#meeting-detail .primary-button').click();
    assert(await page.locator('.quick-booking').isVisible());
    await page.locator('#quick-date-trigger').click();
    await page.locator('.calendar-next').click();
    await page.locator('.quick-calendar .calendar-grid button').first().click();
    await page.locator('.quick-calendar .calendar-done').click();
    await page.locator('.quick-booking .slot:not(:disabled)').nth(0).click();
    await page.locator('.quick-booking .slot:not(:disabled)').nth(1).click();
    assert.equal(await page.locator('#quick-total').innerText(), '¥360');
    await page.locator('#quick-name').fill('回归测试');
    await page.locator('#quick-phone').fill('13800000000');
    await page.locator('#quick-booking-form input[type="checkbox"]').check();
    await page.locator('.quick-booking-footer button').click();
    assert(await page.locator('#booking-record-detail').isVisible());
    assert.match(await page.locator('#booking-record-detail').innerText(), /¥360/);
    await page.reload();
    await show('my-bookings');
    assert.equal(await page.locator('#my-bookings .booking-record').count(), 1);
    await page.locator('#my-bookings .reservation-main').click();
    assert(await page.locator('#meeting-detail').isVisible());
    await page.getByRole('button', { name: '查看本次预约', exact: true }).click();
    await page.getByRole('button', { name: '取消预约', exact: true }).click();
    assert.match(await page.locator('#booking-record-detail').innerText(), /已取消/);
    await show('home');
    await page.locator('#home-consult-open').click();
    await page.locator('#contact-submit').click();
    assert.match(await page.locator('#contact-modal [role="status"]').innerText(), /姓名/);
    await page.locator('#contact-name').fill('咨询测试');
    await page.locator('#contact-phone').fill('13800000000');
    await page.locator('#contact-email').fill('invalid');
    await page.locator('#contact-note').fill('<script>测试文本</script>');
    await page.locator('#contact-modal input[type="checkbox"]').check();
    await page.locator('#contact-submit').click();
    assert.match(await page.locator('#contact-modal [role="status"]').innerText(), /邮箱/);
    await page.locator('#contact-email').fill('');
    await page.locator('#contact-submit').click();
    assert(await page.locator('#service-record-detail').isVisible());
    assert.match(await page.locator('#service-record-detail').innerText(), /已保存/);
    assert.equal(await page.locator('#service-record-detail script').count(), 0);
    await show('visitor');
    const visitor = page.locator('#visitor .form-card input');
    await visitor.nth(0).fill('访客测试');
    await visitor.nth(1).fill('13800000000');
    assert.equal(await page.locator('#visitor .required-hint').count(), 0);
    assert.equal(await visitor.nth(2).getAttribute('required'), null);
    await page.locator('#visitor-date').click();
    while(await page.locator('.service-calendar-month b').textContent() !== '2027年1月') {
      await page.getByRole('button', { name: '下个月', exact: true }).click();
    }
    await page.getByRole('button', { name: '2027年1月2日', exact: true }).click();
    await page.getByRole('spinbutton', { name: '小时', exact: true }).fill('14');
    await page.getByRole('spinbutton', { name: '分钟', exact: true }).fill('00');
    await page.locator('#date-confirm').click();
    await page.locator('#visitor input[type="checkbox"]').check();
    await page.locator('#visitor .primary-button').click();
    assert.match(await page.locator('#service-record-detail').innerText(), /2027-01-02/);
    assert.match(await page.locator('#service-record-detail').innerText(), /未填写/);
    await show('repair');
    await page.locator('#repair .primary-button').click();
    assert.match(await page.locator('#repair [role="status"]').innerText(), /问题描述/);
    assert.equal(await page.locator('#repair .required-hint').count(), 0);
    assert.equal(await page.locator('#repair select').first().getAttribute('required'), null);
    assert.equal(await page.locator('#repair .service-select-trigger').first().getAttribute('aria-required'), 'false');
    const repairInputs = page.locator('#repair .form-card input');
    assert.equal(await repairInputs.nth(0).getAttribute('required'), null);
    assert.equal(await repairInputs.nth(1).getAttribute('required'), null);
    await repairInputs.nth(2).fill('13800000000');
    await page.locator('#repair textarea').fill('照明损坏');
    await page.locator('#repair input[type="checkbox"]').check();
    await page.locator('#repair .primary-button').click();
    assert.match(await page.locator('#service-record-detail').innerText(), /照明损坏/);
    await page.reload();
    await show('visitor-records');
    assert.equal(await page.locator('#visitor-records .booking-record').count(), 1);
    assert.equal(await page.locator('#visitor-records > .service-notice').count(), 0);
    await show('repair-records');
    assert.equal(await page.locator('#repair-records .booking-record').count(), 1);
    await show('profile');
    await page.locator('.profile-login').click();
    assert.match(await page.locator('#local-identity').innerText(), /访客身份/);
    await page.locator('.nav-back').click();
    assert(await page.locator('#profile').isVisible());
    await page.locator('#profile .profile-stats [data-page="repair-records"]').click();
    assert(await page.locator('#repair-records').isVisible());
    await page.locator('.nav-back').click();
    assert(await page.locator('#profile').isVisible());
    await page.getByRole('button', { name: /隐私与授权/ }).click();
    await page.getByRole('button', { name: '清除全部记录', exact: true }).click();
    assert.equal(await page.evaluate(() => MiniStore.data.bookings.length), 0);
    await show('my-bookings');
    assert.equal(await page.locator('#my-bookings .booking-record').count(), 2);
    assert.equal(await page.locator('#my-bookings .reservation-notice').count(), 0);
    assert.deepEqual(await page.locator('#my-bookings .reservation-name').allTextContents(), ['榫卯会议室', '云杉会议室']);
    // Simulate a storage failure: no phantom record or success page may be produced.
    await show('home');
    await page.locator('#home-consult-open').click();
    await page.locator('#contact-name').fill('存储测试');
    await page.locator('#contact-phone').fill('13800000000');
    await page.locator('#contact-email').fill('test@example.com');
    await page.locator('#contact-note').fill('失败时不应生成记录');
    await page.locator('#contact-modal input[type="checkbox"]').check();
    await page.evaluate(() => { MiniStore.save = () => false; });
    await page.locator('#contact-submit').click();
    assert.match(await page.locator('#contact-modal [role="status"]').innerText(), /保存失败/);
    assert.equal(await page.evaluate(() => MiniStore.data.consultations.length), 0);
    await page.reload();
    await show('meeting');
    await page.getByRole('button', { name: '预订榫卯会议室', exact: true }).click();
    assert.match(await page.locator('#quick-room-meta').innerText(), /8人.*80/);
    await page.locator('.quick-booking-close').click();
    assert.deepEqual(errors, []);
    console.log('PASS: filters, correct detail data, both booking entries, multi-slot pricing, persistence, cancellation, consultation validation, safe text, visitor/repair records, identity disclosure, return navigation, clearing records and storage failure rollback; no page errors.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
