const {chromium}=require('C:/Users/sunlei-it/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto('http://127.0.0.1:8765/index.html');
 assert.equal(await page.locator('.entry').count(),2,'统一入口应保持客户/园区两类角色');
 await page.goto('http://127.0.0.1:8765/customer.html#match');
 await page.waitForSelector('.smart-card');
 assert((await page.locator('.smart-card').count())>=2,'智能找房应返回多个结果');
 await page.locator('[data-v4="toggle-compare"]').nth(0).click();
 await page.locator('[data-v4="toggle-compare"]').nth(1).click();
 await page.locator('[data-v4="show-compare"]').click();
 assert(await page.locator('dialog[open]').isVisible(),'方案对比弹窗应打开');
 await page.locator('[data-v4="close-dialog"]').click();
 await page.goto('http://127.0.0.1:8765/customer.html#partner');
 await page.waitForSelector('#partner-form');
 await page.fill('[name="company"]','云岭工业');
 await page.fill('[name="clientPhone"]','13933334444');
 await page.fill('[name="need"]','260㎡研发办公，计划年内入驻');
 await page.selectOption('[name="room"]',{index:1});
 await page.check('.consent input');
 await page.locator('#partner-form button[type="submit"]').click();
 await page.waitForTimeout(150);
 assert((await page.locator('.report-status').first().textContent()).includes('云岭工业'),'渠道报备应进入我的报备');
 await page.goto('http://127.0.0.1:8765/admin.html');
 await page.waitForSelector('#app');
 assert((await page.locator('h1').first().textContent()).includes('经营驾驶舱'),'管理端默认进入驾驶舱');
 for(const item of [['企业研判','企业研判'],['智能匹配','智能匹配'],['带看与报价','带看与报价'],['渠道报备','渠道报备']]){
   await page.getByRole('button',{name:item[0],exact:true}).click();
   await page.waitForTimeout(80);
   assert((await page.locator('h1').first().textContent()).includes(item[1]),item[0]+' 页面应可访问');
 }
 assert((await page.locator('#app').textContent()).includes('云岭工业'),'客户渠道报备应同步到园区端');
 await page.getByRole('button',{name:'智能匹配',exact:true}).click();
 await page.waitForSelector('.match-card');
 await page.locator('.match-card button').filter({hasText:'安排带看'}).first().click();
 await page.waitForSelector('#editform');
 await page.locator('button[type="submit"][form="editform"]').click();
 await page.waitForTimeout(120);
 assert((await page.locator('h1').first().textContent()).includes('带看与报价'),'安排带看后应进入带看页');
 const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});
 await mobile.goto('http://127.0.0.1:8765/customer.html#match');await mobile.waitForSelector('.smart-card');
 const overflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+1);
 assert.equal(overflow,false,'客户移动端不应横向溢出');
 if(errors.length)console.error('BROWSER_ERRORS',JSON.stringify(errors,null,2));
 assert.deepEqual(errors,[],'浏览器不应有脚本错误');
 console.log(JSON.stringify({checks:14,smartCards:await page.locator('.match-card').count(),errors},null,2));
 await browser.close();
})().catch(async e=>{console.error(e);process.exit(1)});
