const M=ParkModel;
const old={render,drawer,resourcePage,leadPage,clientPage,rulePage,mobile,commissionPage,publishPage};
try{db=JSON.parse(localStorage.getItem('park-leasing-v4'))||M.init(seed)}catch{db=M.init(seed)}
window.save=function(){M.sync(db);try{localStorage.setItem('park-leasing-v4',JSON.stringify(db))}catch{toast('存储空间不足，本次修改仅保留在当前页面')}};
window.btn=(t,fn,p=false)=>'<button class="btn '+(p?'primary btn-primary':'btn-outline')+'" onclick="'+esc(fn)+'">'+t+'</button>';
window.act=function(fn,msg){try{let result=fn();save();closeModal();render();if(msg)toast(msg);return result}catch(e){toast(e.message);return false}};
window.render=function(){M.sync(db);old.render();document.querySelectorAll('.panel,.metric').forEach(e=>e.classList.add('card-glass'))};
window.drawer=function(t,b,f=''){old.drawer(t,b,f);document.querySelector('.drawerhead button')?.setAttribute('aria-label','关闭详情')};
window.days=end=>M.diff(db.today,end);
window.expiring=()=>db.contracts.filter(c=>!['已退租','待退租结算'].includes(c.status)&&!c.next&&days(c.end)<=db.rules.days);
const money=n=>'¥ '+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const rows=obj=>Object.entries(obj).map(([k,v])=>'<div class="row"><span class="muted">'+k+'</span><b>'+esc(v)+'</b></div>').join('');
const arg=JSON.stringify;
function flow(){return '<div class="flow">'+[['01','房源准备','rooms'],['02','获客分派','leads'],['03','商机跟进','opps'],['04','合同签约','contracts'],['05','客户入驻','clients'],['06','续约结算','renew']].map(([n,t,p])=>btn('<small>'+n+'</small>'+t+' →','go('+arg(p)+')',p===page)).join('')+'</div>'}
window.roomPage=function(){
 let total=db.rooms.length,n=db.rooms.filter(r=>['已出租','临期'].includes(r.status)).length,ss=['空置','预占','待入驻','已出租','临期','待释放'],groups={};
 db.rooms.forEach(r=>{let key=r.id.split('-')[0]+' 座 · '+Math.floor(Number(r.id.split('-')[1])/100)+' F';(groups[key]??=[]).push(r)});
 return heading('招商工作台','星桥科创园 · 房源、客户与合同协同管理',btn('移动房态盘',"mobile('rooms')")+btn('招商简报','brief()',true))+flow()+
 '<div class="metrics">'+metric('房源总数',total,'间','挂牌总面积 '+db.rooms.reduce((a,r)=>a+r.area,0).toLocaleString()+' ㎡')+metric('实际出租率',(n/total*100).toFixed(1),'%','生效占用 '+n+' 间 / 全部 '+total+' 间')+metric('可招商空间',db.rooms.filter(r=>r.status==='空置').length,'间','预占、待入驻及待释放不计入')+metric('到期续约待办',expiring().length,'份','预警窗口 '+db.rules.days+' 天')+'</div>'+
 '<div class="panel"><div class="panelhead"><div><h2>可视化房态盘</h2><small>点击房间查看合同、预占及历史记录</small></div>'+btn('房源清单',"go('resources')")+'</div><div class="filters">'+select(['全部状态',...ss],roomFilter,'roomFilter=this.value;render()')+'<input id="roomsearch" placeholder="搜索房号或客户" value="'+esc(keyword)+'">'+btn('查询',"keyword=$('#roomsearch').value;render()")+'</div><div class="legend">'+ss.map(s=>'<span><i class="state-dot s-'+s+'"></i>'+s+' '+db.rooms.filter(r=>r.status===s).length+'</span>').join('')+'</div>'+
 Object.entries(groups).map(([f,rr])=>{let rs=rr.filter(r=>(roomFilter==='全部状态'||r.status===roomFilter)&&JSON.stringify(r).toLowerCase().includes(keyword.toLowerCase()));return rs.length?'<section class="space-floor"><span class="floor-name">'+f+'</span><div class="space-rooms">'+rs.map(roomCard).join('')+'</div></section>':''}).join('')+'</div>'+
 '<div class="bottomgrid"><div class="panel"><h2>招商转化概况</h2>'+['初步接洽','实地带看','商务谈判','已签约'].map(s=>'<div class="row"><span>'+s+'</span><b>'+db.opps.filter(o=>o.stage===s).length+' 个商机</b></div>').join('')+'</div><div class="panel"><h2>协同待办</h2>'+[['待跟进线索',db.leads.filter(l=>l.status==='待跟进').length,'leads'],['退租待结算',db.contracts.filter(c=>c.status==='待退租结算').length,'contracts'],['佣金待审批',db.commissions.filter(c=>c.status==='待审批').length,'commission']].map(([t,n,p])=>'<div class="row"><span>'+t+'</span>'+btn(n+' 项 →','go('+arg(p)+')')+'</div>').join('')+'</div></div>'
};
window.roomCard=r=>'<button class="room s-'+r.status+'" onclick="'+esc('roomDetail('+arg(r.id)+')')+'"><div class="room-top"><b>'+esc(r.id)+'</b><span>'+r.status+'</span></div><span>'+esc(r.client||'可预约 · 可签约')+'</span><em><span>'+r.area+' ㎡</span><span>'+r.price+' 元/㎡/月</span></em></button>';
window.roomDetail=function(id){let r=db.rooms.find(r=>r.id===id),h=db.holds.find(h=>h.room===id&&h.status==='有效');drawer('房源详情 · '+esc(id),'<div class="detailhero"><h2>'+id+'</h2>'+badge(r.status)+'<p>'+r.area+' ㎡ · '+esc(r.tag)+'</p></div>'+rows({挂牌租金:money(r.price)+' /㎡/月',运营主体:r.operator,当前客户:r.client||'暂无'})+(h?'<div class="spec section-title">预占至 '+h.until+' · '+esc(h.owner)+'</div>':'')+'<h3 class="section-title">关联合同</h3>'+table(['编号','租期','状态',''],db.contracts.filter(c=>c.room===id).map(c=>tr([c.no,c.start+' ~ '+c.end,badge(c.status),btn('查看','contractDetail('+c.id+')')]))),btn('维护资源','editResource('+arg(id)+')')+(r.status==='空置'?btn('预占房源','holdForm('+arg(id)+')')+btn('发起签约','newContract('+arg(id)+')',true):h?btn('释放预占','act(()=>M.cancelHold(db,'+h.id+'),"预占已释放")')+btn('签约','newContract('+arg(id)+')',true):''))};
window.holdForm=id=>form('预占房源 · '+esc(id),field('客户名称','client')+field('招商负责人','owner','林晓','text',db.staff.map(s=>s.name))+'<div class="field full spec">按规则 V'+db.rules.version+' 保留 '+db.rules.lock+' 天，截止 '+M.add(db.today,db.rules.lock)+'。</div>','act(()=>M.hold(db,'+arg(id)+',data().client,data().owner),"房源已预占")','确认预占');
window.editResource=function(id){let r=db.rooms.find(r=>r.id===id);form('租赁资源 · '+id,field('面积（㎡）','area',r.area,'number')+field('挂牌租金（元/㎡/月）','price',r.price,'number')+field('标签','tag',r.tag)+field('运营主体','operator',r.operator)+'<div class="field full spec">仅修改挂牌资源，已签合同保留面积与租金快照。</div>','act(()=>M.resource(db,'+arg(id)+',data()),"挂牌信息已更新，合同快照未变")');document.querySelector('.drawerfoot').insertAdjacentHTML('afterbegin',btn('变更历史','resourceHistory('+arg(id)+')'))};
window.resourceHistory=function(id){let r=db.rooms.find(r=>r.id===id);drawer('资源变更记录 · '+id,table(['日期','原租金 → 新租金','原主体 → 新主体'],r.changes.map(c=>tr([c.date,c.old.price+' → '+c.next.price,esc(c.old.operator)+' → '+esc(c.next.operator)]))))};
window.resourcePage=function(){return heading('租赁资源','挂牌资源与合同价格分离，保留每一次变更。',btn('导入 CSV','importRooms()')+btn('导出资源',"exportData('rooms')"))+'<div class="panel">'+searchFilters(['空置','预占','待入驻','已出租','临期','待释放'])+table(['房源','面积','挂牌租金','标签','运营主体','状态','操作'],db.rooms.filter(matches).map(r=>tr([r.id,r.area+'㎡',money(r.price),esc(r.tag),esc(r.operator),badge(r.status),btn('维护','editResource('+arg(r.id)+')')])))+'</div>'};
window.newLead=function(){form('录入招商线索',field('客户名称','name')+field('联系人','contact')+field('手机号（用于去重）','phone','','tel')+field('意向需求','need')+field('获客来源','source','','text',db.rules.sources.split(','))+'<div class="field full spec">手机号相同合并申请；自动分派跳过缺席人员。合并后保留原负责人。</div>',"act(()=>M.lead(db,data()),'已保存线索；重复客户合并申请记录')",'保存线索')};
window.addLead=d=>M.lead(db,d);
window.convertLead=id=>act(()=>M.convert(db,id),'已转为商机，重复转换会被阻止');
window.leadDetail=function(id){let l=db.leads.find(l=>l.id===id);drawer('意向客户 · '+esc(l.name),rows({联系人:l.contact,电话:l.phone,负责人:l.owner,分派依据:l.assignment,状态:l.status,无效原因:l.reason||'—'})+'<h3 class="section-title">申请记录 · '+l.applications.length+' 次</h3>'+table(['日期','来源','意向'],l.applications.map(a=>tr([a.date,esc(a.source)+(a.adId?' / 海报 '+a.adId:''),esc(a.need)]))),l.status==='待跟进'?btn('标记无效','invalidate('+id+')')+btn('转商机','convertLead('+id+')',true):'')};
window.leadPage=()=>old.leadPage()+'<div class="panel"><h2>分派记录</h2>'+table(['客户','负责人','分派依据','申请次数'],db.leads.map(l=>tr([esc(l.name),esc(l.owner),esc(l.assignment),l.applications.length])))+'</div>';
window.applyAd=function(id){let a=db.ads.find(a=>a.id===id),r=db.rooms.find(r=>r.id===a.room);if(a.status!=='已发布'||r.status!=='空置')return toast('房源已失效或被占用，暂不可申请');form('预约看房 · '+a.room,field('客户名称','name')+field('联系人','contact')+field('手机号','phone','','tel')+field('意向需求','need',a.room+' · 预约看房'),'submitApplication('+id+')','提交预约')};
window.submitApplication=function(id){let a=db.ads.find(a=>a.id===id);act(()=>{M.sync(db);if(a.status!=='已发布'||db.rooms.find(r=>r.id===a.room).status!=='空置')throw Error('提交失败，房源已失效');M.lead(db,{...data(),source:'小程序申请',adId:id});a.submissions++;a.intents=new Set(db.leads.filter(l=>l.applications.some(p=>p.adId===id)).map(l=>l.phone)).size},'预约成功，重复申请已归入原客户')};
window.toggleAd=id=>act(()=>{let a=db.ads.find(a=>a.id===id);if(a.status!=='已发布'&&db.rooms.find(r=>r.id===a.room).status!=='空置')throw Error('仅空置房源可以发布');a.status=a.status==='已发布'?'草稿':'已发布'},'推广状态已更新');
window.publishPage=()=>old.publishPage()+'<div class="panel"><h2>推广转化口径</h2>'+table(['推广','浏览次数 PV','意向客户（手机号去重）','提交次数','房源状态'],db.ads.map(a=>tr([esc(a.title),a.views,a.intents,a.submissions,badge(db.rooms.find(r=>r.id===a.room).status)])))+'</div>';
window.mobile=function(mode,id){if(mode==='rooms'){drawer('移动房态盘','<div class="phone"><div class="phonehead"><h2>星桥科创园 · 房态</h2><p>共 '+db.rooms.length+' 间 · 与管理端同步</p></div><div class="phonebody"><div class="mobilegrid">'+db.rooms.map(roomCard).join('')+'</div></div></div>');return}old.mobile(mode,id);if(mode==='ad'){let a=db.ads.find(a=>a.id===id);if(a.status!=='已发布'||db.rooms.find(r=>r.id===a.room).status!=='空置'){let b=[...document.querySelectorAll('.phone button')].find(b=>b.textContent==='预约看房');if(b){b.disabled=true;b.textContent='房源已失效 · 不可申请'}}}};
window.newContract=function(room='',oppId=0,previous=0){
 let prev=db.contracts.find(c=>c.id===previous),o=db.opps.find(o=>o.id===oppId),h=db.holds.find(h=>h.room===room&&h.status==='有效'),opts=prev?[prev.room]:db.rooms.filter(r=>['空置','预占'].includes(r.status)).map(r=>r.id);
 if(!opts.length)return toast('暂无可签约房源');let r=db.rooms.find(r=>r.id===(room||opts[0])),start=prev?M.add(prev.end,1):'2026-10-01',end=prev?(Number(start.slice(0,4))+1)+start.slice(4):'2027-09-30';
 form(prev?'续约 · 新建关联合同':'新建租赁合同','<div class="field full spec">'+(prev?'原合同 '+prev.no+' 保留不变；续约从原到期次日开始。':'签约前校验租期冲突、预占客户和报价底线。')+'</div>'+field('承租客户','name',prev?.name||o?.name||h?.client||'')+field('租赁房源','room',r.id,'text',opts)+field('起租日','start',start,'date')+field('到期日','end',end,'date')+field('单价（元/㎡/月）','price',prev?.price||r.price,'number')+field('押金（元）','deposit',prev?.deposit||r.area*r.price*3,'number')+field('免租期（天）','free',prev?0:30,'number')+field('每周年递增（%）','increase',prev?.increase||3,'number')+'<div class="field full spec">试算口径：自然月实际天数逐日折算；起租日起免租；每周年递增；月金额四舍五入到分。押金单列。</div><div class="field full" id="billpreview"></div>','submitContract('+oppId+','+previous+')','确认签约');document.querySelector('.drawerfoot').insertAdjacentHTML('afterbegin',btn('试算账单','previewBills()'))
};
window.previewBills=function(){if(!$('#editform').reportValidity())return;try{let d=data(),r=db.rooms.find(r=>r.id===d.room),bs=M.bills({...d,area:r.area});$('#billpreview').innerHTML='<h3>逐期租金预览</h3>'+table(['月份','租赁天数 / 免租','租金'],bs.map(b=>tr([b.month,b.days+' / '+b.freeDays,money(b.rent)])))+'<b>租金合计 '+money(bs.reduce((n,b)=>n+b.rent,0))+' · 押金 '+money(d.deposit)+'</b>'}catch(e){toast(e.message)}};
window.submitContract=function(oppId,previous){act(()=>{let d=data();if(previous){let p=db.contracts.find(c=>c.id===previous);if(p.next)throw Error('该合同已续约');if(d.start!==M.add(p.end,1))throw Error('续约起租日须为原到期次日');d.name=p.name;d.room=p.room}M.sign(db,d,oppId,previous);page='contracts'},'签约完成，已保存条款和账单快照')};
window.createContract=o=>submitContract(o,0);
window.contractPage=function(){return heading('合同管理','合同条款、计租明细、历史版本与退出结算',btn('导出合同',"exportData('contracts')")+btn('新建合同','newContract()',true))+flow()+'<div class="metrics">'+metric('有效合同',db.contracts.filter(c=>c.status!=='已退租').length,'份','含待生效与续约合同')+metric('临期续约',expiring().length,'份','已续约的原合同停止提醒')+metric('退租待结算',db.contracts.filter(c=>c.status==='待退租结算').length,'份','结清后再释放空间')+metric('合同版本',db.contracts.reduce((n,c)=>n+c.versions.length+1,0),'个','历史快照可查')+'</div><div class="panel">'+searchFilters(['已签约','履约中','待退租结算','已退租'])+table(['合同 / 客户','房源 / 面积','租期','条款单价','版本','状态','操作'],db.contracts.filter(matches).map(c=>tr(['<b>'+c.no+'</b><br><small>'+esc(c.name)+'</small>',c.room+' / '+c.area+'㎡',c.start+'<br>'+c.end,money(c.price),'V'+(c.versions.length+1)+(c.previous?' · 续约':''),badge(c.status),btn('查看详情','contractDetail('+c.id+')')])))+'</div>'};
window.contractDetail=function(id,tab='terms'){
 let c=db.contracts.find(c=>c.id===id),body='',tabs=[['terms','合同条款'],['bills','计租与调整'],['versions','历史版本'],['files','附件归档']];
 if(tab==='terms')body=rows({房源:c.room+' / '+c.area+'㎡',租期:c.start+' 至 '+c.end,条款单价:money(c.price)+' /㎡/月',押金:money(c.deposit),免租期:c.free+' 天',周年递增:c.increase+'%',关联续约:c.next?db.contracts.find(x=>x.id===c.next)?.no:c.previous?db.contracts.find(x=>x.id===c.previous)?.no:'暂无'})+(c.exit?'<div class="spec section-title">退租 '+c.exit.date+' · 待收欠款 '+money(c.exit.due)+' · 应退押金 '+money(c.exit.refund)+'<br>'+esc(c.exit.reason)+'<br>'+esc(c.exit.receipt||'尚未结算')+'</div>':'');
 if(tab==='bills')body='<div class="spec">自然月实际天数折算，起租日起免租，每周年递增。原始账单保留，调价差额另列。</div>'+table(['月份','租赁 / 免租天数','原始应收'],c.bills.map(b=>tr([b.month,b.days+' / '+b.freeDays,money(b.rent)])))+'<h3 class="section-title">变更调整单</h3>'+table(['月份','原金额','变更后','差额'],c.adjustments.map(a=>tr([a.month,money(a.old),money(a.next),money(a.diff)])));
 if(tab==='versions')body='<div class="spec">当前 V'+(c.versions.length+1)+'；旧版本只读保留，续约生成独立关联合同。</div>'+table(['版本','快照日期','原单价','操作'],c.versions.map(v=>tr(['V'+v.version,v.savedAt,money(v.snapshot.price),btn('查看快照','snapshotView('+id+','+v.version+')')])))+'<div class="timeline">'+c.history.map(h=>'<p>'+esc(h)+'</p>').join('')+'</div>';
 if(tab==='files')body='<p class="muted">附件保存在本机浏览器，单文件最多 1 MB。不包含电子签章。</p><input type="file" id="attachment" accept=".pdf,.doc,.docx,.png,.jpg" onchange="attachFile('+id+')"><h3 class="section-title">已归档附件</h3>'+table(['名称','大小','操作'],c.attachments.map((f,i)=>tr([esc(f.name),Math.ceil(f.size/1024)+' KB',btn('下载','downloadAttachment('+id+','+i+')')])));
 let foot=btn('导出快照','downloadArchive('+id+')');if(c.status==='待退租结算')foot+=btn('完成退租结算','settleForm('+id+')',true);else if(c.status!=='已退租')foot+=(!c.next?btn('退租','exitContract('+id+')'):'')+btn('变更','changeContract('+id+',false)')+(!c.next?btn('续约','changeContract('+id+',true)',true):'');
 drawer(c.no+' · '+esc(c.name),'<div class="detailhero"><h2>'+esc(c.name)+'</h2>'+badge(c.status)+' <small>归档合同 · V'+(c.versions.length+1)+'</small></div><div class="tabs">'+tabs.map(([k,t])=>'<button class="'+(k===tab?'active':'')+'" onclick="'+esc('contractDetail('+id+','+arg(k)+')')+'">'+t+'</button>').join('')+'</div>'+body,foot)
};
window.snapshotView=function(id,v){let snap=db.contracts.find(c=>c.id===id).versions.find(x=>x.version===v).snapshot;window.snapshot=snap;drawer('只读历史快照 · V'+v,'<pre class="snapshot">'+esc(JSON.stringify(snap,null,2))+'</pre>',btn('下载版本',"download('合同历史版本.json',JSON.stringify(window.snapshot,null,2),'application/json')"))};
window.changeContract=function(id,renew){let c=db.contracts.find(c=>c.id===id);if(renew)return newContract(c.room,0,id);form('合同变更 · 保留旧版本',field('新单价','price',c.price,'number')+field('生效日','effective',M.add(db.today,1),'date')+field('变更原因','reason')+'<div class="field full spec">生效日前不调整；原始账单保留，差额生成调整明细。</div>','act(()=>M.amend(db,'+id+',data()),"新版本和调整明细已保存")')};
window.exitContract=function(id){let c=db.contracts.find(c=>c.id===id);form('退租 · 结算前保留占用',field('退租日期','date',db.today,'date')+field('待收欠款','due',0,'number')+field('应退押金','refund',c.deposit,'number')+field('退租原因','reason')+'<div class="field full spec">提交后进入待退租结算；欠款与退款确认后才释放房源。</div>','act(()=>M.requestExit(db,'+id+',data()),"退租已提交，结算前不释放房源")','提交退租')};
window.settleForm=function(id){let c=db.contracts.find(c=>c.id===id);form('退租结算确认','<div class="field full spec">确认已收欠款 '+money(c.exit.due)+'、已退押金 '+money(c.exit.refund)+'。</div>'+field('收付结算凭证','receipt'),'act(()=>M.settleExit(db,'+id+',data().receipt),"结算完成，房源已释放")','确认结清并释放')};
window.attachFile=function(id){let f=$('#attachment').files[0];if(!f)return;if(f.size>1048576)return toast('原型附件限 1 MB');let reader=new FileReader();reader.onload=()=>{let c=db.contracts.find(c=>c.id===id);c.attachments.push({name:f.name,size:f.size,url:reader.result});c.history.push(db.today+' 归档附件 '+f.name);save();contractDetail(id,'files');toast('附件已归档')};reader.readAsDataURL(f)};
window.downloadAttachment=function(id,i){let f=db.contracts.find(c=>c.id===id).attachments[i],a=document.createElement('a');a.href=f.url;a.download=f.name;a.click()};
window.editClient=function(id){let c=db.clients.find(c=>c.id===id);form('客户维护 · '+esc(c.name),field('联系人','contact',c.contact)+field('客户类型','type',c.type,'text',['企业客户','个人客户'])+field('物业客服','service',c.service,'text',['','王静','赵敏','刘洋'])+field('备注','note',c.note||'无')+'<div class="field full spec">'+esc(c.history.join('；')||'暂无状态变更')+'</div>','act(()=>{let c=db.clients.find(c=>c.id==='+id+');let d=data();if(d.service&&c.status==="未成交")throw Error("未成交客户需先签约");Object.assign(c,d);M.stamp(db,"客户维护",c.name)},"信息已保存，状态按合同生效情况更新")');document.querySelector('.drawerfoot').insertAdjacentHTML('afterbegin',btn('历史合同','closeModal();go("contracts");keyword='+arg(c.name)+';render()'))};
window.clientPage=()=>old.clientPage()+'<div class="panel"><h2>客户生命周期</h2><p class="muted">合同生效且分配客服后为已入驻；未来生效合同保持待入驻；最后一份合同结算退租后变为已搬离。</p></div>';
window.rulePage=function(){return old.rulePage().replace('原型展示配置留存；折扣审批与保留期自动释放需在开发阶段接入。','签约校验报价底线；预占按保留期到期，在房态刷新时释放。')+'<div class="rulegrid"><div class="panel"><h2>招商员出勤</h2>'+db.staff.map((s,i)=>'<div class="row"><span>'+esc(s.name)+' · 顺序 '+(i+1)+'</span>'+btn(s.present?'在岗 · 设为缺席':'缺席 · 设为在岗','act(()=>{db.staff['+i+'].present=!db.staff['+i+'].present},"出勤已更新")')+'</div>').join('')+'</div><div class="panel"><h2>规则版本</h2>'+table(['版本','生效日','适用范围'],db.ruleVersions.map(v=>tr(['V'+v.version,v.effective,esc(v.scope)])))+'</div></div>'};
window.saveRules=function(){if(!$('#rulesform').reportValidity())return;act(()=>M.rules(db,Object.fromEntries(new FormData($('#rulesform')))),'新版本规则已生效，存量合同与分派保持不变')};
window.renewPage=function(){return heading('续约与到期提醒','识别临期合同，跟进续约，并追踪通知结果。',btn('预警规则',"go('rules')")+btn('模拟失败','runReminders(true)')+btn('运行临期检查','runReminders(false)',true))+'<div class="notice"><span>演示日期 '+db.today+' · 提前 '+db.rules.days+' 天 · '+esc(db.rules.notify)+'</span>'+btn('调整演示日期','dateForm()')+'</div><div class="panel"><h2>待续约合同</h2>'+table(['合同 / 客户','房源','到期日','剩余天数','操作'],expiring().map(c=>tr([c.no+'<br>'+esc(c.name),c.room,c.end,badge(days(c.end)<0?'已到期':days(c.end)+' 天'),btn('发起续约','changeContract('+c.id+',true)')])))+'</div><div class="panel"><div class="panelhead"><h2>通知记录</h2><small>唯一键：合同 + 到期日 + 接收方</small></div>'+table(['通知','接收方','状态','尝试次数','操作'],db.notifications.map(n=>tr([esc(n.text),esc(n.receiver),badge(n.status),n.attempts,n.status==='发送失败'?btn('重试','act(()=>M.retry(db,'+n.id+'),"重试成功，沿用原通知")'):'—'])))+'<p class="muted section-title">本地通知模拟。重复检查不新增同一通知，续约后停止旧合同提醒。</p></div>'};
window.runReminders=function(f){let n;act(()=>{n=M.remind(db,f)},'检查完成');toast(n?'新增 '+n+' 条通知'+(f?'，模拟发送失败，可重试':''):'无新增通知，同一通知已去重')};
window.dateForm=()=>form('演示日期',field('业务日期','today',db.today,'date')+'<div class="field full spec">调整日期可验证预占过期、合同生效、续约提醒和入驻状态联动。</div>',"act(()=>{db.today=data().today;M.stamp(db,'调整演示日期',db.today)},'日期已更新')");
window.newCommission=function(){form('新建佣金申请',field('渠道编号','channelId',String(db.channels[0].id),'text',db.channels.map(c=>String(c.id)))+field('租赁合同','contract','','text',db.contracts.filter(c=>c.status!=='已退租').map(c=>c.no))+field('月份','month',db.today.slice(0,7),'month')+'<div class="field full spec">'+db.channels.map(c=>c.id+'：'+esc(c.name)+' / '+esc(c.no)+' / '+c.rate+' 个月租金').join('<br>')+'<br>按合同面积与条款单价计算，保存标准快照。</div>',"act(()=>M.commission(db,data()),'申请已提交，等待审批')",'提交申请')};
window.payCommission=id=>form('确认佣金发放',field('银行流水 / 发放凭证','receipt'),'act(()=>M.pay(db,'+id+',data().receipt),"发放已记录，重复结算会被阻止")','确认发放');
window.approveCommission=function(id){let c=db.commissions.find(c=>c.id===id);form('佣金审批','<div class="field full spec">'+esc(c.agencyContract)+'<br>合同月租 '+money(c.base)+' × '+c.rate+' = '+money(c.amount)+'</div>'+field('审批结果','status','待结算','text',['待结算','已驳回'])+field('审批意见','result','合同与标准核对无误'),'act(()=>{let c=db.commissions.find(c=>c.id==='+id+');if(c.status!=="待审批")throw Error("申请已处理");Object.assign(c,data());c.history.push(db.today+" "+c.status+" "+c.result)},"审批结果已保存")')};
window.commissionPage=()=>old.commissionPage()+'<div class="panel"><div class="panelhead"><h2>渠道与中介合同</h2>'+btn('新增渠道','channelForm()',true)+'</div>'+table(['渠道','中介合同','计佣标准','操作'],db.channels.map(c=>tr([esc(c.name),esc(c.no),c.rate+' 个月租金',btn('维护','channelForm('+c.id+')')])))+'</div>';
window.channelForm=function(id){let c=db.channels.find(c=>c.id===id)||{name:'',no:'',rate:1};form('渠道与分佣标准',field('中介名称','name',c.name)+field('中介合同编号','no',c.no)+field('月租金倍数','rate',c.rate,'number'),'act(()=>{let d=data(),c=db.channels.find(c=>c.id==='+(id||0)+');if(c)Object.assign(c,d,{rate:+d.rate});else db.channels.push({...d,rate:+d.rate,id:Date.now()})},"渠道标准已保存，既有佣金快照不变")')};
window.importRooms=function(){drawer('批量导入房源','<p>五列 CSV 模板，失败定位到行，整批校验后写入。同编号更新挂牌属性，合同快照不变。</p><div class="spec section-title">编号示例 A-101，面积大于零，租金不得为负。</div><input type="file" accept=".csv" id="csvfile"><div class="section-title">'+btn('下载模板','downloadRoomTemplate()')+'</div><div id="importerrors"></div>',btn('校验并导入','readImport()',true))};
window.downloadRoomTemplate=()=>download('房源导入模板.csv','\uFEFFid,area,price,tag,operator\r\nB-101,120,65,精装修,星桥园区运营有限公司','text/csv;charset=utf-8');
window.readImport=async function(){let f=$('#csvfile').files[0];if(!f)return toast('请选择文件');let lines=(await f.text()).replace(/^\uFEFF/,'').trim().split(/\r?\n/),errors=[],seen=new Set();if(lines[0]!=='id,area,price,tag,operator')errors.push('第 1 行：表头须为 id,area,price,tag,operator');let rr=lines.slice(1).map((line,i)=>{let a=line.split(',').map(s=>s.trim());if(a.length!==5)errors.push('第 '+(i+2)+' 行：须为 5 列');if(!/^[A-Z]+-\d{3,4}$/.test(a[0]))errors.push('第 '+(i+2)+' 行：房源编号无效');if(seen.has(a[0]))errors.push('第 '+(i+2)+' 行：编号重复');seen.add(a[0]);if(!a[1]||!Number.isFinite(+a[1])||+a[1]<=0)errors.push('第 '+(i+2)+' 行：面积须为正数');if(!a[2]||!Number.isFinite(+a[2])||+a[2]<0)errors.push('第 '+(i+2)+' 行：租金须为非负数');return a});if(!rr.length)errors.push('没有待导入数据');if(errors.length){$('#importerrors').innerHTML='<div class="spec section-title">'+errors.map(esc).join('<br>')+'</div>';return}act(()=>rr.forEach(([id,area,price,tag,operator])=>{if(db.rooms.some(r=>r.id===id))M.resource(db,id,{area:+area,price:+price,tag,operator});else db.rooms.push({id,area:+area,price:+price,tag,operator,status:'空置',client:'',changes:[]})}),'导入 '+rr.length+' 条，房态与统计已同步')};
window.auditView=()=>drawer('操作记录',table(['日期','对象','操作'],db.audit.map(a=>tr([a.date,esc(a.entity),esc(a.action)]))));
window.brief=function(){let n=db.rooms.filter(r=>['已出租','临期'].includes(r.status)).length;window.report='招商简报 · '+db.today+'\n\n房源 '+db.rooms.length+' 间 / 已出租 '+n+' 间\n出租率 '+(n/db.rooms.length*100).toFixed(1)+'%\n空置 '+db.rooms.filter(r=>r.status==='空置').length+' 间\n意向客户 '+db.leads.length+' 位 / 申请 '+db.leads.reduce((n,l)=>n+l.applications.length,0)+' 次\n临期合同 '+expiring().length+' 份\n\n建议：跟进空置资源意向、及时续约，结清退租后释放房源。\n实际出租包含生效租约，不含预占和未来生效租约。';drawer('招商简报','<pre class="snapshot">'+esc(window.report)+'</pre>',btn('下载简报',"download('招商简报.txt',window.report)",true))};
document.title='360智慧园区 · 招商与合同管理原型';
document.querySelector('.brand').innerHTML='<span class="logo">360</span><span>智慧园区<small>招商与合同管理</small></span>';
document.querySelector('header>div').textContent='星桥科创园 / 招商与合同管理';
document.querySelector('.topright').insertAdjacentHTML('afterbegin',btn('操作记录','auditView()'));
navs[0][0]='招商管理';navs[0][3]='招商工作台';navs[2][0]='';navs[7][3]='续约与提醒';navs[6][0]='合同管理';
save();render();

/* Shared forms escape handlers before placing them in HTML attributes. */
window.form=function(title,fields,submit,label='保存'){drawer(title,'<form id="editform" class="formgrid" onsubmit="'+esc('event.preventDefault();'+submit)+'">'+fields+'<button hidden type="submit"></button></form>','<button class="primary" type="submit" form="editform">'+label+'</button>');document.querySelectorAll('#editform .field').forEach((f,i)=>{let l=f.querySelector('label'),control=f.querySelector('input,select,textarea');if(l&&control){control.id='edit-field-'+i;l.htmlFor=control.id}})};
const originalEditAd=editAd;
window.editAd=function(id){originalEditAd(id);};
const baseSync=M.sync;
M.sync=function(d){d.ads.forEach(a=>{a.submissions??=0;a.views??=0;a.intents??=0});baseSync(d)};

const renderEnhanced=render;
window.render=function(){renderEnhanced();document.querySelectorAll('#nav i').forEach(i=>i.setAttribute('aria-hidden','true'))};
render();

window.convertLead=id=>act(()=>{M.convert(db,id);page='opps'},'已转为商机，负责人保持不变');

let commissionMonth='全部月份';
const basicMatches=matches;
window.matches=r=>basicMatches(r)&&(page!=='commission'||commissionMonth==='全部月份'||r.month===commissionMonth);
const commissionView=commissionPage;
window.commissionPage=function(){return commissionView().replace('<div class="panel">','<div class="panel"><div class="filters"><span>结算月份</span>'+select(['全部月份',...new Set(db.commissions.map(c=>c.month))].sort().reverse(),commissionMonth,'commissionMonth=this.value;render()')+'<small>月度筛选同时作用于表格与导出</small></div>')};
const genericExport=exportData;
window.exportData=function(key){
 if(key!=='commissions')return genericExport(key);
 let selected=db.commissions.filter(matches),headers=['月份','渠道','中介合同','租赁合同','房间数','面积㎡','月租金','分佣倍数','佣金','已结金额','未结金额','状态','发放凭证'];
 let csv=[headers,...selected.map(c=>[c.month,c.channel,c.agencyContract,c.contract,c.rooms,c.area,c.base,c.rate,c.amount,c.paid,M.round(c.amount-c.paid),c.status,c.result||''])].map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');
 download('佣金月报-'+commissionMonth+'.csv','\uFEFF'+csv,'text/csv;charset=utf-8');toast('已导出 '+selected.length+' 条佣金记录');
};
document.addEventListener('keydown',event=>{
 if(event.key!=='Tab'||!document.querySelector('.drawer'))return;
 const focusable=[...document.querySelectorAll('.drawer button,.drawer input,.drawer select,.drawer textarea,.drawer a')].filter(e=>!e.disabled&&e.getClientRects().length);
 const first=focusable[0],last=focusable.at(-1);
 if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}
 else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}
});
