const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const browser = await chromium.launch({
    headless: true,
    executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
  });
  try {
    const page = await browser.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('dialog', dialog => dialog.accept());
    await page.goto(pathToFileURL(path.join(__dirname, 'miniprogram-view.html')).href);
    assert.deepEqual(await page.locator('#home .space-info .meta > span').allTextContents(), ['6F','可分割']);
    assert.equal(await page.locator('#contact-modal .form-row .required-mark').count(), 3);
    assert.equal(await page.locator('#contact-modal .form-row [aria-required="true"]').count(), 3);
    assert.equal(await page.locator('.agreement .required-mark').count(), 0);
    assert.equal(await page.locator('#quick-booking-form input[type="checkbox"]').evaluate(el => el.required), true);
    assert.equal(await page.locator('#contact-email').evaluate(el => el.required), false);
    assert.equal(await page.locator('label[for="quick-purpose"] .required-mark').count(), 0);
    assert.match(await page.locator('label[for="quick-purpose"]').textContent(), /选填/);
    const show = id => page.evaluate(id => window.__showMiniPage(id), id);
    for (const id of ['my-bookings','visitor-records','repair-records']) {
      await show(id);
      assert.equal(await page.locator(`#${id} .booking-record`).count(), 2);
      await page.locator(`#${id} .booking-record`).first().click();
      assert.match(await page.locator('.screen > section:not(.hidden)').last().textContent(), /示例|样例/);
    }
    assert.deepEqual(await page.evaluate(() => ['bookings','visitors','repairs'].map(k => MiniStore.data[k].length)), [0,0,0]);
    assert.deepEqual(await page.locator('.profile-stats b').allTextContents(), ['2','2','2']);
    await show('repair');
    const locationSelect = page.locator('#repair .service-select-trigger').first();
    await locationSelect.click();
    await page.locator('.service-select-panel.open').getByRole('option', { name: 'B座', exact: true }).click();
    assert.equal(await page.locator('#repair select').first().inputValue(), 'B座');
    assert.equal(await locationSelect.getAttribute('aria-expanded'), 'false');
    await locationSelect.press('ArrowDown');
    assert.equal(await page.locator('.service-select-panel.open [aria-selected="true"]').textContent(), 'B座');
    await page.keyboard.press('ArrowUp');
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#repair select').first().inputValue(), 'A座');
    await locationSelect.click();
    await page.keyboard.press('Escape');
    assert.equal(await locationSelect.getAttribute('aria-expanded'), 'false');
    await show('feedback');
    await page.locator('#feedback .service-select-trigger').click();
    await page.locator('.service-select-panel.open').getByRole('option', { name: '物业投诉', exact: true }).click();
    assert.equal(await page.locator('#feedback select').inputValue(), '物业投诉');
    await page.locator('#feedback textarea').fill('选填电话留空的反馈');
    await page.locator('#feedback .primary-button').click();
    assert.equal(await page.evaluate(() => MiniStore.data.feedback.length), 0);
    await page.locator('#feedback .agreement input').check();
    await page.locator('#feedback .primary-button').click();
    assert.equal(await page.evaluate(() => MiniStore.data.feedback.length), 1);
    const filter = async (section, index, text) => {
      const label = page.locator(`#${section} .meeting-filters label`).nth(index);
      await label.locator('.filter-trigger').click();
      await label.getByRole('button', { name: text, exact: true }).click();
    };
    await show('spaces');
    await filter('spaces', 0, 'B座');
    assert.equal(await page.locator('.building-card:visible').count(), 1);
    await page.locator('.building-card:visible').click();
    await page.locator('[data-space-detail="B-503"]').click();
    assert.match(await page.locator('#space-detail-meta').innerText(), /^B座/);
    await page.locator('.nav-back').click();
    assert(await page.locator('#building-detail').isVisible());
    await show('spaces');
    await filter('spaces', 0, 'D座');
    assert.equal(await page.locator('.building-card:visible').count(), 0);
    assert(await page.getByText('暂无符合条件的结果，请调整筛选条件。', { exact: true }).first().isVisible());
    await show('meeting');
    await filter('meeting', 0, 'C区');
    assert.equal(await page.locator('.meeting-list-card:visible').count(), 1);
    assert.match(await page.locator('.meeting-list-card:visible').innerText(), /云杉/);
    await filter('meeting', 0, '全部区域');
    await page.locator('.meeting-card-detail[data-room-detail="远山路演厅"]').click();
    assert.match(await page.locator('#meeting-detail > .meta').innerText(), /24人/);
    assert.match(await page.locator('#meeting-detail .detail-price').innerText(), /180/);
    await page.locator('#meeting-detail .primary-button').click();
    assert(await page.locator('.quick-booking').isVisible());
    await page.locator('#quick-date-trigger').click();
    await page.locator('.calendar-next').click();
    await page.locator('.quick-calendar .calendar-grid button').first().click();
    await page.locator('.quick-calendar .calendar-done').click();
    await page.locator('.quick-booking .slot:not(:disabled)').nth(0).click();
    await page.locator('.quick-booking .slot:not(:disabled)').nth(1).click();
    assert.equal(await page.locator('#quick-total').innerText(), '¥360');
    await page.locator('#quick-name').fill('回归测试');
    await page.locator('#quick-phone').fill('13800000000');
    await page.locator('#quick-booking-form input[type="checkbox"]').check();
    await page.locator('.quick-booking-footer button').click();
    assert(await page.locator('#booking-record-detail').isVisible());
    assert.match(await page.locator('#booking-record-detail').innerText(), /¥360/);
    await page.reload();
    await show('my-bookings');
    assert.equal(await page.locator('#my-bookings .booking-record').count(), 1);
    await page.locator('#my-bookings .booking-record').click();
    await page.getByRole('button', { name: '取消本地演示预约', exact: true }).click();
    assert.match(await page.locator('#booking-record-detail').innerText(), /已取消/);
    await show('home');
    await page.locator('#home-consult-open').click();
    await page.locator('#contact-submit').click();
    assert.match(await page.locator('#contact-modal [role="status"]').innerText(), /姓名/);
    await page.locator('#contact-name').fill('咨询测试');
    await page.locator('#contact-phone').fill('13800000000');
    await page.locator('#contact-email').fill('invalid');
    await page.locator('#contact-note').fill('<script>测试文本</script>');
    await page.locator('#contact-modal input[type="checkbox"]').check();
    await page.locator('#contact-submit').click();
    assert.match(await page.locator('#contact-modal [role="status"]').innerText(), /邮箱/);
    await page.locator('#contact-email').fill('');
    await page.locator('#contact-submit').click();
    assert(await page.locator('#service-record-detail').isVisible());
    assert.match(await page.locator('#service-record-detail').innerText(), /未发送/);
    assert.equal(await page.locator('#service-record-detail script').count(), 0);
    await show('visitor');
    const visitor = page.locator('#visitor .form-card input');
    await visitor.nth(0).fill('访客测试');
    await visitor.nth(1).fill('13800000000');
    await visitor.nth(2).fill('B503');
    await page.locator('#visitor-date').click();
    await page.locator('.service-date-input').fill('2027-01-02T14:00');
    await page.locator('#date-confirm').click();
    await page.locator('#visitor input[type="checkbox"]').check();
    await page.locator('#visitor .primary-button').click();
    assert.match(await page.locator('#service-record-detail').innerText(), /2027-01-02/);
    await show('repair');
    await page.locator('#repair .primary-button').click();
    assert.match(await page.locator('#repair [role="status"]').innerText(), /房间/);
    const repairInputs = page.locator('#repair .form-card input');
    await repairInputs.nth(0).fill('B503');
    await repairInputs.nth(1).fill('报修测试');
    await repairInputs.nth(2).fill('13800000000');
    await page.locator('#repair textarea').fill('照明损坏');
    await page.locator('#repair input[type="checkbox"]').check();
    await page.locator('#repair .primary-button').click();
    assert.match(await page.locator('#service-record-detail').innerText(), /照明损坏/);
    await page.reload();
    await show('visitor-records');
    assert.equal(await page.locator('#visitor-records .booking-record').count(), 1);
    await show('repair-records');
    assert.equal(await page.locator('#repair-records .booking-record').count(), 1);
    await show('profile');
    await page.locator('.profile-login').click();
    assert.match(await page.locator('#local-identity').innerText(), /未接入/);
    await page.locator('.nav-back').click();
    assert(await page.locator('#profile').isVisible());
    await page.locator('#profile [data-page="repair"].profile-menu-row').click();
    await page.locator('.nav-back').click();
    assert(await page.locator('#profile').isVisible());
    await page.getByRole('button', { name: /隐私与授权/ }).click();
    await page.getByRole('button', { name: '清除本机全部记录', exact: true }).click();
    assert.equal(await page.evaluate(() => MiniStore.data.bookings.length), 0);
    await show('my-bookings');
    assert.equal(await page.locator('#my-bookings .booking-record').count(), 2);
    assert.match(await page.locator('#my-bookings').textContent(), /演示样例/);
    // Simulate a storage failure: no phantom record or success page may be produced.
    await show('home');
    await page.locator('#home-consult-open').click();
    await page.locator('#contact-name').fill('存储测试');
    await page.locator('#contact-phone').fill('13800000000');
    await page.locator('#contact-email').fill('test@example.com');
    await page.locator('#contact-note').fill('失败时不应生成记录');
    await page.locator('#contact-modal input[type="checkbox"]').check();
    await page.evaluate(() => { MiniStore.save = () => false; });
    await page.locator('#contact-submit').click();
    assert.match(await page.locator('#contact-modal [role="status"]').innerText(), /保存失败/);
    assert.equal(await page.evaluate(() => MiniStore.data.consultations.length), 0);
    await page.reload();
    await show('meeting');
    await page.getByRole('button', { name: '预订榫卯会议室', exact: true }).click();
    assert.match(await page.locator('#quick-room-meta').innerText(), /8人.*80/);
    await page.locator('.quick-booking-close').click();
    assert.deepEqual(errors, []);
    console.log('PASS: filters, correct detail data, both booking entries, multi-slot pricing, persistence, cancellation, consultation validation, safe text, visitor/repair records, identity disclosure, return navigation, clearing records and storage failure rollback; no page errors.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
